### ISSUE TITLE
No GPU devices with CUDA support available.

### ISSUE THREAD

**Issue by xSirCastic** [SunOner/sunone_aimbot_cpp#10]
I have AMD GPU and when i tried to open AI.exe, im getting an error No GPU devices with CUDA support available.

**Comment by NANOBYTECOMPUTERS** [comment]
I dont beleive rocm is yet supported on the cpp version, However it is on the python version.

**Comment by xSirCastic** [comment]
is there any way i can use this with AMD GPU?

**Comment by Kprobem** [comment]
you can try DML, if you're use intel or amd gpu
